### ISSUE TITLE
More advanced vehicle data

### ISSUE THREAD

**Issue by callummoffat** [SupernovaApps/Petrolhead#11]
Several users have suggested adding more advanced data to the Vehicle class. The following are the items they suggested:

- [ ] Trim package
- [ ] Engine choice
- [ ] Type of car

This information needs to be added to the app backend, and also the the PCL.

**Comment by phxchristian** [comment]
The type of car helps with finding specific parts, i.e. the Wagon rear window regulators are not the same as the Sedan rear window regulators.  I can see Petrolhead potentially developing into a car based social network / part warehouse / maintenance tracker.  It would be awesome to get everything in one app.  Too many people break apps apart when unifying them would save a lot of time when it comes to the end user and their experience.  Please let me know when you've fixed the year selection and I'll try out the new beta and let you know what else I find.

**Comment by callummoffat** [comment]
I've fixed the year selection in the latest released version (no longer in beta). Download here: https://www.microsoft.com/store/apps/9NBLGGH1RJQT

**Comment by phxchristian** [comment]
Dashboard should be more than just a Get Parts link.  It should show upcoming maintenance schedules (oil & tuneups).  It should show a graph of mpg based on past 15 fill ups at least.  It should show a graph of last performed maintenance / maybe even an area for suggested maintenance depending on mileage. (i.e. water pump & timing belts are recommended every 30-50,000 miles on most cars).

**Comment by callummoffat** [comment]
I'm aware of this. I'm working on rewriting the code (again) to use Xamarin.Forms, which makes my job easier.

**Comment by callummoffat** [comment]
I'm working on new stuff. At this point, this project is basically a one man band, and that limits the speed of development.

**Comment by callummoffat** [comment]
This has been added. However, a sync error occurs on startup, because I haven't updated the backend. When the new codebase launches, the backend will have the new stuff.
