### ISSUE TITLE
[Discussion] Petrolhead pricing

### ISSUE THREAD

**Issue by callummoffat** [SupernovaApps/Petrolhead#12]
I've opened this issue to discuss Petrolhead's pricing. What payment model do you think would suit best? What price point should Petrolhead aim for? These are all questions I'd like answered, as I urgently need funding for this and other projects. What do you think?

**Comment by phxchristian** [comment]
It's nowhere near ready to charge people to download yet.  I think when it's all finished, you can make a free version with ads and limited functionality, and you can make a paid version with no ads and advanced functionality, i.e. support for multiple cars, support for more than 1 year of service.  You might be able to even get people to pay a one time fee of 7.00 to unlock everything or make certain items ala carte.

**Comment by callummoffat** [comment]
I know it's not ready. I'm discussing options for what to charge when it is
ready. I'm relatively new to app development (in comparison with many), and
I'd like to get opinion's on what would be an appropriate pricing for the
finished product. You following?


*Callum Moffat*
App Developer
Windows 10 Enthusiast
__________________________________
Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by ajmcateer** [comment]
Whats the money going to go too, I personally haven't seen an open source app charge before.

**Comment by callummoffat** [comment]
Funding the development of Petrolhead, as well as any future apps I develop.


*Callum Moffat*
App Developer
Windows 10 Enthusiast
__________________________________
Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by ajmcateer** [comment]
I know there are some fees for apple and I am sure some other things might crop up, but you alone aren't developing this app. Its open source, so I am not a fan of you taking money from an open source app to fund future developments for yourself. I have spent the past two years learning to program and I was excited to start helping on this but not if you are going to profit off of everyone else's work. If you want to sell it to cover costs I am fine with that but maybe donate the rest to charity.

**Comment by callummoffat** [comment]
That is the plan for the funds. Sorry if I didn't explain that well enough.


*Callum Moffat*
App Developer
Windows 10 Enthusiast
__________________________________
Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by callummoffat** [comment]
I will indeed be donating to charity all of the funds from Petrolhead (that
aren't used to fund things such as entry into Google Play/App Store,
etcetera). Good idea - I'll do that.


*Callum Moffat*
App Developer
Windows 10 Enthusiast
__________________________________
Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by callummoffat** [comment]
You know what? You're absolutely right. I shouldn't profit off something that isn't just my work; that's dead wrong. 

Petrolhead will be free to download and use. Absolutely free! And that's my final decision.

**Comment by callummoffat** [comment]
So, I'm reconsidering the issue of pricing, based on the following facts:

- This project needs funding.
- I need funding for personal stuff and development projects.
- Other developers for this project probably also need funding.

**Comment by callummoffat** [comment]
So, I've developing this funding model:
Free (ad-supported) version with support for up to 2 vehicles, and missing some advanced features.
$3.99 IAP which unlocks the rest of the functionality, and disables the advertising.

(Don't start commenting yet, I'm not done...)

**Comment by callummoffat** [comment]
The funds would then be split as follows:

- 70% of each months funding (if any) goes towards Petrolhead's development and maintenance.
- 20% of the month's funding (if there is any) is split between the top 4 contributors for that month (not including me). If less than 4 contributors (not including me) contribute in any given month, the left-over portion of the funds towards Petrolhead.
- 10% goes in my direction, for personal stuff, as well as any other development projects I may start in future. 

Give me your thoughts, please.

**Comment by ajmcateer** [comment]
That sounds fine to me.

**Comment by callummoffat** [comment]
Thanks for your input, @ajmcateer. The new pricing model will start being used once the final release based on this new codebase is finished.

I'm going to keep this issue open for a while to get other people's input.

**Comment by callummoffat** [comment]
Created a wiki page detailing the funding model: https://github.com/SupernovaApps/Petrolhead/wiki/Funding-Model
