### ISSUE TITLE
Add Vehicle UX

### ISSUE THREAD

**Issue by ajmcateer** [SupernovaApps/Petrolhead#15]
Any mock ups for the UI?

**Comment by callummoffat** [comment]
Not yet. I have an idea in my idea. Hang on - I'll draw one up, and get back to you.

**Comment by callummoffat** [comment]
Here's the mockup of the Add Vehicle user interface as I envision it. Feel free to implement, and make changes.

![cci04052016](https://cloud.githubusercontent.com/assets/13494563/14271499/dc7ed8aa-fb4d-11e5-8933-82d929c3ac92.jpg)

**Comment by ajmcateer** [comment]
Looks good I can add this tomorrow.

**Comment by callummoffat** [comment]
Thanks! That will be awesome!!!

**Comment by callummoffat** [comment]
Any progress, @ajmcateer?

**Comment by ajmcateer** [comment]
@callummoffat I am new to git having trouble pulling the newest upstream changes to my personal branch.

**Comment by callummoffat** [comment]
I'm working on the UX at the moment, so that'll be fine.

**Comment by ajmcateer** [comment]
Are you working on the add vehicle page right now? Don't want to duplicate work.

**Comment by callummoffat** [comment]
Not yet. I'm mainly coding the backend. The only UI I've added is the page header with an add button. Allows me to test the functionality.

**Comment by callummoffat** [comment]
I'll commit in a second...

**Comment by callummoffat** [comment]
The underlying view model for the Add Vehicle UI is now in place. Feel free to code the UX now; just make it utilise this view-model.
