### ISSUE TITLE
We should consider using a more powerful MVVM library

### ISSUE THREAD

**Issue by ajmcateer** [SupernovaApps/Petrolhead#16]
Template10's library is pretty minimal and doesn't include support for messaging. Message is the cleanest way I can think of to do a few things(like add vehicles back to the mainpage from the add page). I have used MVV Light before and liked it, but there are others as well.

Just a thought, not sure of the entire scope of the change.

**Comment by callummoffat** [comment]
I use both T10's MVVM capabilities and MVVM Light in Petrolhead. I recognize that the Messaging is the easiest way to do a lot of things.
