### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by QuentinSc** [SupernovaApps/Petrolhead#8]
Hello,

It's me or a file is missing?
VehicleEditorPage.xaml ?

![image](https://cloud.githubusercontent.com/assets/16439299/13962822/01c26f0a-f063-11e5-8540-9626e38bb2bd.png)

**Comment by callummoffat** [comment]
Let me take a look.


*Callum Moffat*
App Developer
Windows 10 Enthusiast
__________________________________
Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by callummoffat** [comment]
Yes, it would appear so. I'll correct this today.


*Callum Moffat*
App Developer
Windows 10 Enthusiast
__________________________________
Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by callummoffat** [comment]
I have corrected this now. Thanks for reporting!
