### ISSUE TITLE
[Xamarin Shared Project] Azure Mobile Apps support needs to be added

### ISSUE THREAD

**Issue by callummoffat** [SupernovaApps/Petrolhead#9]
I've just created a new project based on Xamarin.Forms. It needs to have a link to the Mobile Apps backend to work. I think encapsulating this in a wrapper class that handles it for you is probably best. Maybe something based off ObservableCollection<T>? In any case, this needs to be finished before anything else can be started.

**Comment by snickler** [comment]
Hmm, I'm not clear on this :)

**Comment by callummoffat** [comment]
So, the shared Xamarin.Forms project needs a MobileServiceClient instance to link it to the backend. I prefer to make it easier by encapsulating the client in a wrapper class that handles all the hard stuff. :-)

**Comment by callummoffat** [comment]
I've added this to the code.
